#### Outlier detection

In [1]:
import sys
import pandas as pd
sys.path.insert(0, "../")

from src.preprocessing.outlier_detection import OutlierDetection

In [2]:
df_data = pd.read_csv('../results/preprocessing/02_dataset_preprocessing.csv')
detector = OutlierDetection(df_data=df_data)

##### Exploring outliers with local method

In [3]:
outliers_iqr = detector.detect_outliers_iqr()
outliers_iqr

           Column  Outlier Value
0     cholesterol          294.0
1     cholesterol          294.0
2     cholesterol          294.0
3     cholesterol          237.0
4     cholesterol          294.0
...           ...            ...
1000          bmi           56.6
1001          bmi           46.0
1002          bmi           49.5
1003          bmi           47.6
1004          bmi           46.9

[1005 rows x 2 columns]

#### Outlier detection with global method

In [4]:
result_if = detector.filter_isolation_forest()
outliers_if = result_if[result_if['outlier'] == -1] # predicciÃ³n de outliers (-1 para outliers, 1 para normales)
outliers_if

,age,blood pressure,cholesterol,max heart rate,plasma glucose,skin_thickness,insulin,bmi,outlier,Residence_type_Rural,Residence_type_Urban,chest pain type,exercise angina,gender,heart_disease,hypertension,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,40,140.0,294.0,172.0,108.00,43.0,92.0,19.0,-1,0,1,2,0,1,0,0,0,0,1,0
9,48,120.0,294.0,142.0,77.00,37.0,90.0,18.0,-1,0,1,2,0,0,0,0,0,0,1,0
15,54,120.0,294.0,150.0,96.00,64.0,82.0,23.0,-1,0,1,2,0,0,0,0,0,0,1,0
19,36,120.0,294.0,160.0,121.00,78.0,137.0,20.0,-1,0,1,2,0,1,0,0,0,0,1,0
22,44,150.0,294.0,150.0,98.00,66.0,129.0,21.0,-1,0,1,2,1,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,53,105.0,196.0,142.0,175.92,97.0,129.0,26.9,-1,1,0,0,0,1,0,0,0,0,0,1
6499,40,120.0,167.0,157.0,191.15,68.0,99.0,42.7,-1,0,1,0,0,1,0,0,0,0,0,1
6509,82,117.0,185.0,157.0,179.38,30.0,84.0,27.7,-1,0,1,0,0,1,0,0,1,0,0,0
6510,70,93.0,182.0,189.0,193.88,97.0,92.0,24.3,-1,1,0,0,0,1,0,0,1,0,0,0
6518,81,137.0,178.0,140.0,58.72,27.0,92.0,40.0,-1,1,0,0,0,0,0,0,0,0,0,1

In [5]:
result_if['outlier'].value_counts()

outlier
 1    5896
-1     655
Name: count, dtype: int64