In [72]:
import sys
import pandas as pd
sys.path.insert(0, "../")

from src.xai.apply_counterfactuals import CounterfactualExplainer

#### Load dataset

In [59]:
df_data = pd.read_csv("../results/classification/10_classification_data.csv")
data_values = df_data.drop(columns=['label'])
responses= df_data['label']

#### Generate counterfactuals by class

In [73]:
explainer = CounterfactualExplainer("../results/classification/10_classification_data.csv")
query_instance = explainer.train_data.iloc[[0]] # Seleccionar una instancia de consulta

counterfactuals_list = explainer.generate_and_show_counterfactuals(query_instance, total_cfs=19)

100%|██████████| 1/1 [00:22<00:00, 22.91s/it]

Query instance (original outcome : 0)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0

Diverse Counterfactual set (new outcome: 0)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,1,0,0,1,1,0,0,0,2,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
1,0,0,0,1,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
2,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,0.523616,-0.245259,70,0
3,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,-0.300000,-0.222222,-0.053333,0.243902,70,0
4,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,0.329605,-0.053333,0.243902,70,0
5,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.319239,70,0
6,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.433580,0.464286,-0.222222,-0.053333,-0.493905,70,0
7,1,0,0,0,0,1,1,0,0,1,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
8,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
9,0,0,0,0,0,1,1,0,0,0,0,1.018613,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
10,0,0,0,0,0,1,1,0,0,0,0,0.302220,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
11,0,0,0,0,0,1,1,0,0,0,0,0.056073,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
12,0,0,0,0,0,1,1,0,0,0,0,-1.272368,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
13,0,0,0,0,0,1,1,0,0,1,0,0.371429,-0.616676,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
14,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.122428,70,0
15,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,2.350048,0.243902,70,0
16,0,0,0,0,0,1,1,0,0,0,0,0.881950,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0
17,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.000000,-0.222222,-0.053333,0.243902,70,0
18,0,0,1,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.961645,70,0

100%|██████████| 1/1 [00:00<00:00,  3.77it/s]

Query instance (original outcome : 0)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0

Diverse Counterfactual set (new outcome: 1)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,1,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,35,1
1,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,34,1
2,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,47,1
3,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,0.325475,0.243902,48,1
4,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,35,1
5,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.777908,28,1
6,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,33,1
7,1,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,28,1
8,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,-1.000000,-0.222222,-0.053333,0.243902,35,1
9,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.498551,48,1
10,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,44,1
11,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,45,1
12,0,0,0,0,0,1,1,0,0,0,0,1.190637,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,41,1
13,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,45,1
14,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,48,1
15,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,44,1
16,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.590693,33,1
17,0,0,0,0,0,1,1,0,0,1,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,41,1
18,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,38,1

100%|██████████| 1/1 [00:29<00:00, 29.91s/it]

Query instance (original outcome : 0)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0

Diverse Counterfactual set (new outcome: 2)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,61,2
1,0,0,0,1,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,60,2
2,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,2.875110,0.464286,-0.222222,-0.053333,0.243902,65,2
3,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,67,2
4,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,59,2
5,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,65,2
6,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.100000,-0.222222,-0.053333,0.243902,66,2
7,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,63,2
8,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.217753,0.464286,-0.222222,-0.053333,0.243902,61,2
9,0,0,0,0,0,1,1,1,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,59,2
10,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.314420,61,2
11,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,2.450537,0.464286,-0.222222,-0.053333,0.243902,61,2
12,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,69,2
13,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,64,2
14,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,-0.187717,69,2
15,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,0.871203,-0.053333,0.243902,67,2
16,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,59,2
17,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,66,2
18,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,66,2

100%|██████████| 1/1 [00:00<00:00,  3.90it/s]

Query instance (original outcome : 0)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,70,0

Diverse Counterfactual set (new outcome: 3)

,gender,exercise angina,hypertension,heart_disease,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,chest pain type,blood pressure,bmi,cholesterol,insulin,max heart rate,plasma glucose,skin_thickness,age,label
0,0,0,0,0,1,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,54,3
1,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,1.345635,0.243902,49,3
2,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,52,3
3,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.929775,52,3
4,0,0,0,0,0,1,1,0,0,0,0,0.371429,-0.323299,0.172414,0.464286,-0.222222,-0.053333,0.243902,57,3
5,0,0,1,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,56,3
6,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.622234,57,3
7,0,0,0,0,0,1,1,0,0,0,4,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,55,3
8,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,51,3
9,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,55,3
10,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,57,3
11,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,51,3
12,0,0,0,0,0,1,0,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,54,3
13,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,54,3
14,1,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,57,3
15,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,56,3
16,0,0,0,0,0,1,1,0,0,0,0,-1.467085,0.361702,0.172414,0.464286,-0.222222,-0.053333,0.243902,57,3
17,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,-0.400000,-0.222222,-0.053333,0.243902,49,3
18,0,0,0,0,0,1,1,0,0,0,0,0.371429,0.361702,0.172414,-0.600000,-0.222222,-0.053333,0.243902,53,3